version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: debug
      MYSQL_DATABASE: parcial_db
      MYSQL_USER: debug
      MYSQL_PASSWORD: debug
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: